module.exports = function(){

    return [
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2413,
        "NUME_PRODUS": "Samsung Galaxy S9 Plus",
        "NAME": "Samsung Galaxy S9 Plus 256 GB Negru 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2414,
        "NUME_PRODUS": "Huawei P20",
        "NAME": "Huawei P20 Roz 4G",
        "Producator": "Huawei",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2415,
        "NUME_PRODUS": "LG G7 ThinQ 4G",
        "NAME": "LG G7 ThinQ Negru 4G",
        "Producator": "LG",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2416,
        "NUME_PRODUS": "Samsung Galaxy S9",
        "NAME": "Samsung Galaxy S9 64 GB Violet 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2417,
        "NUME_PRODUS": "iPhone 7",
        "NAME": "iPhone 7 128GB Negru 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2418,
        "NUME_PRODUS": "iPhone 7",
        "NAME": "iPhone 7 32GB Negru 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2419,
        "NUME_PRODUS": "Samsung Galaxy S9 Plus",
        "NAME": "Samsung Galaxy S9 Plus 64 GB Violet 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2420,
        "NUME_PRODUS": "Nokia 2",
        "NAME": "Nokia 2 Negru 4G",
        "Producator": "Nokia",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2421,
        "NUME_PRODUS": "Vodafone Smart N8",
        "NAME": "Vodafone Smart N8 Auriu 4G",
        "Producator": "Vodafone",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "5-5.4 inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2422,
        "NUME_PRODUS": "Vodafone Smart N9",
        "NAME": "Vodafone �Smart N9 �Negru",
        "Producator": "Vodafone",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2423,
        "NUME_PRODUS": "Nokia 3.1 4G",
        "NAME": "Nokia 3.1 Negru 4G",
        "Producator": "Nokia",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2424,
        "NUME_PRODUS": "iPhone 7 Plus",
        "NAME": "iPhone 7 Plus 32GB Negru 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2425,
        "NUME_PRODUS": "HTC U11",
        "NAME": "HTC U11 Negru 4G",
        "Producator": "HTC",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack, Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2426,
        "NUME_PRODUS": "Huawei Mate 10 Pro",
        "NAME": "Huawei Mate 10 Pro Negru 4G+",
        "Producator": "huawei",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2427,
        "NUME_PRODUS": "Nokia 3310 2017",
        "NAME": "Nokia 3310 2017 Rosu",
        "Producator": "Nokia",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "Pana in 3.9 inch",
        "Camera": "Sub 5 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2428,
        "NUME_PRODUS": "Samsung GALAXY S7",
        "NAME": "Samsung Galaxy S7 32 GB 4G+ Auriu",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "5-5.4 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2429,
        "NUME_PRODUS": "Vodafone  Smart Mini 7",
        "NAME": "Vodafone �Smart Mini 7 Negru",
        "Producator": "Vodafone",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4-4.4 inch",
        "Camera": "Sub 5 MP",
        "Memorie interna": "Sub 8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2430,
        "NUME_PRODUS": "iPhone SE",
        "NAME": "iPhone SE 32GB �Negru 4G",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa,Mufa Jack",
        "Diagonala Ecran": "4-4.4 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2431,
        "NUME_PRODUS": "Samsung GALAXY Note 8",
        "NAME": "Samsung GALAXY Note 8 4G+ Negru",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2432,
        "NUME_PRODUS": "Nokia 3",
        "NAME": "Nokia 3 Negru Mat 4G",
        "Producator": "Nokia",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2433,
        "NUME_PRODUS": "LG K10 2017",
        "NAME": "LG K10 2017 Negru 4G",
        "Producator": "LG",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,  Mufa Jack",
        "Diagonala Ecran": "5-5.4 inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2434,
        "NUME_PRODUS": "Samsung GALAXY J5 2017",
        "NAME": "Samsung GALAXY J5 2017 Auriu 4G",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,  Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2435,
        "NUME_PRODUS": "Samsung GALAXY J6 2018 4G",
        "NAME": "Samsung GALAXY J6 2018 4G�Negru",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,  Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2436,
        "NUME_PRODUS": "Nokia 3.1 4G",
        "NAME": "Nokia 3.1 Alb 4G",
        "Producator": "Nokia",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2437,
        "NUME_PRODUS": "Samsung Galaxy A6 4G+",
        "NAME": "Samsung Galaxy A6 4G+ Violet",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2438,
        "NUME_PRODUS": "Mobiwire Ayasha",
        "NAME": "Mobiwire Ayasha Negru",
        "Producator": "Mobiwire",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "Pana in 3.9 inch",
        "Camera": "Sub 5 MP",
        "Memorie interna": "Sub 8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2439,
        "NUME_PRODUS": "iPhone 6s",
        "NAME": "iPhone 6s 32GB Roz 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa,Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2440,
        "NUME_PRODUS": "iPhone X",
        "NAME": "iPhone X 256GB Negru 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta, Incarcare Wireless , Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2441,
        "NUME_PRODUS": "Huawei P20 Pro",
        "NAME": "Huawei P20 Pro Negru 4G",
        "Producator": "Huawei",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2442,
        "NUME_PRODUS": "Samsung GALAXY J3 2017",
        "NAME": "Samsung GALAXY J3 2017�Auriu 4G",
        "Producator": "Samsung",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2443,
        "NUME_PRODUS": "Wiko Tommy 2",
        "NAME": "Wiko Tommy 2 Negru",
        "Producator": "Wiko",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "8-10 MP",
        "Memorie interna": "8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2444,
        "NUME_PRODUS": "Samsung Galaxy S8",
        "NAME": "Samsung Galaxy S8 64 GB 4G+ Argintiu",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "16 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2445,
        "NUME_PRODUS": "Samsung Galaxy A6 4G+",
        "NAME": "Samsung Galaxy A6 4G+ Auriu",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2446,
        "NUME_PRODUS": "Sony Xperia XA1",
        "NAME": "Sony Xperia XA1 Negru 4G",
        "Producator": "Sony",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2447,
        "NUME_PRODUS": "Samsung Galaxy S9",
        "NAME": "Samsung Galaxy S9 64 GB Albastru Inchis 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2448,
        "NUME_PRODUS": "Samsung Galaxy A6 Plus",
        "NAME": "Samsung Galaxy A6 Plus 4G+ Negru",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2449,
        "NUME_PRODUS": "HTC U12 Plus",
        "NAME": "HTC U12 Plus Albastru",
        "Producator": "HTC",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack, Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2450,
        "NUME_PRODUS": "Samsung Galaxy A5 2017",
        "NAME": "Samsung Galaxy A5 2017 32GB Negru 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,  Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "Peste 12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2451,
        "NUME_PRODUS": "Samsung Galaxy S9",
        "NAME": "Samsung Galaxy S9 256 GB Negru 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2452,
        "NUME_PRODUS": "Samsung Galaxy S8+",
        "NAME": "Samsung Galaxy S8 Plus 64 GB 4G+ Orchid Grey",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "5-5.4 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2453,
        "NUME_PRODUS": "iPhone 7",
        "NAME": "iPhone 7 32GB Roz 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2454,
        "NUME_PRODUS": "iPhone 8 Plus",
        "NAME": "iPhone 8 Plus 64GB Rosu 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta, Incarcare Wireless , Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2455,
        "NUME_PRODUS": "iPhone SE",
        "NAME": "iPhone SE 32GB �Roz 4G",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta,  Rezistent la Apa,Mufa Jack",
        "Diagonala Ecran": "4-4.4 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2456,
        "NUME_PRODUS": "iPhone 8",
        "NAME": "iPhone�8 64GB�Negru 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta, Incarcare Wireless , Rezistent la Apa",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2457,
        "NUME_PRODUS": "BlackBerry KeyOne Negru 4G",
        "NAME": "BlackBerry Keyone Argintiu 4G",
        "Producator": "BlackBerry",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "10-12 MP",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2458,
        "NUME_PRODUS": "Samsung Galaxy S9",
        "NAME": "Samsung Galaxy S9 64 GB Negru 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2459,
        "NUME_PRODUS": "Samsung GALAXY S7",
        "NAME": "Samsung Galaxy S7 32 GB 4G+ Negru",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "",
        "Camera": "",
        "Memorie interna": "32 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2460,
        "NUME_PRODUS": "Samsung Galaxy S9 Plus",
        "NAME": "Samsung Galaxy S9 Plus 64 GB Albastru Inchis 4G+",
        "Producator": "Samsung",
        "Caracteristici principale": "Senzor Amprenta, Memorie Expandabila,Incarcare Wireless , Rezistent la Apa , Mufa Jack",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2461,
        "NUME_PRODUS": "Vodafone Smart E8",
        "NAME": "Vodafone Smart E8 Albastru 4G",
        "Producator": "Vodafone",
        "Caracteristici principale": "Memorie Expandabila, Mufa Jack",
        "Diagonala Ecran": "4.5-5 inch",
        "Camera": "5-7.9 MP",
        "Memorie interna": "8 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    },
    {
        "DISPLAY_NAME": "Toate Telefoanele",
        "sku_id": 2462,
        "NUME_PRODUS": "iPhone X",
        "NAME": "iPhone�X 256GB Argintiu 4G+",
        "Producator": "Iphone",
        "Caracteristici principale": "Senzor Amprenta, Incarcare Wireless , Rezistent la Apa",
        "Diagonala Ecran": "Peste 5.4inch",
        "Camera": "10-12 MP",
        "Memorie interna": "Peste 64 GB",
        "Disponibil in magazin": "Magazin Vodafone - Bucuresti Magheru"
    }
];
};